controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# index:
#     path: /
#     controller: App\Controller\DefaultController::index

auth:
    path: /api/auth/
    controller: App\Controller\AuthController::Auth
    methods: [POST]

register:
    path: /api/register/
    controller: App\Controller\RegisterController::Register
    methods: [POST]

login:
    path: /api/login/
    controller: App\Controller\LoginController::Login
    methods: [POST]

user_data:
    path: /api/user/
    controller: App\Controller\UserController::GetUserData
    methods: [POST]

user_data_update:
    path: /api/user/
    controller: App\Controller\UserController::PutUserData
    methods: [PUT]

user_data_delete:
    path: /api/user/
    controller: App\Controller\UserController::DeleteUserData
    methods: [DELETE]

cars:
    path: /api/cars/
    controller: App\Controller\CarsController::GetCars
    methods: [POST]

history:
    path: /api/history/
    controller: App\Controller\HistoryController::GetHistory
    methods: [POST]

pay:
    path: /api/pay/
    controller: App\Controller\PayController::Pay
    methods: [POST]